# Generated by Django 4.2.10 on 2024-02-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackingid', models.CharField(default='', max_length=10, null=True)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Activity', models.CharField(choices=[('Parcel Has Been Received And It Is Ready For Shipping!', 'Parcel Has Been Received And It Is Ready For Shipping!'), ('On Transit', 'On Transit'), ('On Hold', 'On Hold'), ('Shipped', 'Shipped'), ('Package Arrived (On Clearance)', 'Package Arrived (On Clearance)')], max_length=200)),
                ('Location', models.CharField(max_length=400)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackingid', models.CharField(default='', max_length=10, null=True, unique=True)),
                ('Estimated_Date_of_Departuer', models.DateField()),
                ('Estimated_Date_of_Arrival', models.DateField()),
                ('Sender_Name', models.CharField(max_length=400)),
                ('Sender_Origin', models.CharField(max_length=200)),
                ('From', models.CharField(max_length=400)),
                ('To', models.CharField(max_length=400)),
                ('Reciver_Name', models.CharField(max_length=400)),
                ('Reciver_Email', models.EmailField(max_length=400)),
                ('Reciver_Address', models.TextField()),
                ('Reciver_Phone', models.CharField(max_length=200)),
                ('Item_Description', models.CharField(max_length=200)),
                ('Weight_And_Dimension', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('timeline', models.ManyToManyField(default='', to='tracking.timeline')),
            ],
        ),
    ]
