# Generated by Django 4.2.10 on 2024-02-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='Activity',
            field=models.CharField(max_length=200),
        ),
    ]
